steps:
  # Step 1: Set up the Google Cloud SDK
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate using Google Cloud service account
        echo $GOOGLE_CREDENTIALS | base64 --decode > tf-modules/gke-cluster/gke-sa.json
        gcloud auth activate-service-account --key-file=tf-modules/gke-cluster/gke-sa.json
        gcloud config set project $PROJECT_ID

  # Step 2: Install Terraform
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        sudo apt update && sudo apt install terraform

  # Step 3: Initialize Terraform (downloads modules and provider plugins)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tf-modules/gke-cluster/
        terraform init

  # Step 4: Plan Terraform deployment
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tf-modules/gke-cluster/
        terraform plan -out=tfplan

  # Step 5: Apply Terraform deployment
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tf-modules/gke-cluster/
        terraform apply -auto-approve tfplan

  # Optional Step: Clean up after apply
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Destroy resources if desired after apply (comment out if not needed)
        # cd tf-modules/gke-cluster/
        # terraform destroy -auto-approve

timeout: '1200s'  # Maximum duration for the build (20 minutes)

options:
  logging: NONE  # Disable logging completely

# Define available substitutions for project and credentials
substitutions:
  _PROJECT_ID: "a-sysops"
  _GOOGLE_CREDENTIALS: "gke-sa.json"
