apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: highway-app
        image: us-west1-docker.pkg.dev/a-sysops/highwy-app/user-service:latest
        ports:
        - containerPort: 8080

